-- AlterTable
ALTER TABLE `product_logs` MODIFY `action` ENUM('CREATED', 'UPDATED', 'UPDATED_COST', 'UPDATED_PRICE', 'RESTOCK', 'SALE_OFFLINE', 'ADJUST_DAMAGE', 'ADJUST_LOST', 'ADJUST_OPNAME') NOT NULL;
