-- AlterTable
ALTER TABLE `service_logs` MODIFY `action` ENUM('CREATED', 'UPDATE_INFO', 'UPDATE_STATUS', 'UPDATE_TECHNICIAN', 'UPDATE_SERVICE_LIST', 'UPDATE_DISCOUNT', 'UPDATE_DOWN_PAYMENT', 'UPDATE_FINANCIALS', 'DELETED', 'RESTORED') NOT NULL;
