-- AlterTable
ALTER TABLE `product_logs` ADD COLUMN `is_voided` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `action` ENUM('CREATED', 'UPDATE_INFO', 'UPDATE_COST', 'UPDATE_PRICE', 'RESTOCK', 'SALE_OFFLINE', 'ADJUST_DAMAGE', 'ADJUST_LOST', 'ADJUST_OPNAME', 'VOID_LOG', 'DELETED', 'RESTORED') NOT NULL;

-- AlterTable
ALTER TABLE `products` ADD COLUMN `deleted_at` DATETIME(3) NULL;
