-- AlterTable
ALTER TABLE `products` MODIFY `category` ENUM('DEVICE', 'LCD', 'BATTERY', 'CONNECTOR', 'FLEXIBLE', 'CAMERA', 'SPEAKER', 'BACKDOOR', 'GLASS', 'IC', 'ACCESSORY', 'OTHER') NOT NULL DEFAULT 'OTHER';
